<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" >
  <xsd:element name="listaSconti">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="Sconto" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="Sconto">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element  ref="Gioco" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
        <xsd:attribute name="id_tipoSconto" typer="xsd:int" use="required"/>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="Gioco">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element nome="id_gioco" type="xsd:int" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
       <xsd:attribute name="valoreSconto" typer="xsd:int" use="optional"/>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>