<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" >

  <xsd:element name="listaCarrelli">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="carrello" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="carrello">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element  ref="gioco" minOccurs="0" maxOccurs="1"/>
      </xsd:sequence>
        <xsd:attribute name="id_user" type="xsd:integer" use="required"/>
        <xsd:attribute name="id_cart" type="xsd:integer" use="required"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="gioco">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element  ref="Titolo"  minOccurs="1" maxOccurs="1"/>
        <xsd:element  ref="prezzo"  minOccurs="1" maxOccurs="1"/>
      </xsd:sequence>
        <xsd:attribute name="id_gioco" type="xsd:integer" use="required"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element  name="Titolo"  type="xsd:string" />
  <xsd:element  name="prezzo"  type="xsd:float" />

</xsd:schema>