<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" >

  <xsd:element name="listaCommenti">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="Gioco" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="Gioco">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element  ref="Commento" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
        <xsd:attribute name="id_gioco" type="xsd:interger" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="Commento">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="text"  minOccurs="1" maxOccurs="1"/>
      </xsd:sequence>
        <xsd:attribute name="id_commento" type="xsd:interger" use="required"/>
        <xsd:attribute name="id_utente" type="xsd:interger" use="required"/>
        <xsd:attribute name="data" type="xsd:string" use="required"/>
        <xsd:attribute name="ora" type="xsd:time" use="required"/>
        <xsd:attribute name="like" type="xsd:interger" use="required"/>
        <xsd:attribute name="dislike" type="xsd:interger" use="required"/>
        <xsd:attribute name="segnalazioni" type="xsd:interger" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element nome="text" type="xsd:string" />
  </xsd:element>
  
</xsd:schema>