<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" >

  <xsd:element name="Associazione_Like_Commenti">
  <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="ref_Commento" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
      </xsd:complexType>
  </xsd:element>
  <xsd:element name="ref_Commento">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="Id_Utente" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="Id_Commento" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="Id_Gioco" minOccurs="1" maxOccurs="1"/>
      </xsd:sequence>
      <xsd:attribute name="flagLike" type="xsd:integer" use="required"/>
      <xsd:attribute name="flagDislike" type="xsd:integer" use="required"/>
    </xsd:complexType>
    </xsd:element>
  <xsd:element name="Id_Utente" type="xsd:integer"/>
  <xsd:element name="Id_Commento" type="xsd:integer"/>
  <xsd:element name="Id_Gioco" type="xsd:integer"/>
  </xsd:schema>