<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" >
    <xsd:element name="LogTransazioniGiochi">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="Transazione" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="Transazione">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="Gioco" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attribute name="IDTransazione" type="xsd:integer" use="required"/>
            <xsd:attribute name="IDGiocatore" type="xsd:integer"/>
            <xsd:attribute name="ModCommentiUsato" type="xsd:float" use="required"/>
            <xsd:attribute name="DataOra" type="xsd:dateTime" use="required"/>
            <xsd:attribute name="PixelIniziali" type="xsd:integer" use="required"/>
        </xsd:complexType>
        </xsd:element>
        <xsd:element name="Gioco">
            <xsd:complexType>
                <xsd:sequence>
                    <xsd:element ref="Titolo" minOccurs="1" maxOccurs="1"/>
                    <xsd:element ref="IDGioco" minOccurs="1" maxOccurs="1"/>
                    <xsd:element ref="Importo" minOccurs="1" maxOccurs="1"/> 
                    <!-- l'importo sara quello calcolato dopo gli sconti -->
                </xsd:sequence>
            </xsd:complexType>
    </xsd:element>
    <xsd:element name="Titolo" type="xsd:string"/>
    <xsd:element name="IDGioco" type="xsd:integer"/>
    <xsd:element name="Importo" type="xsd:float"/>
</xsd:schema>