<?xml version="1.0" encoding="UTF-8"?> 
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"> 

  <xsd:element name="listaUtenti"> 
    <xsd:complexType> 
      <xsd:sequence> 
        <xsd:element ref="Utente" minOccurs="0" maxOccurs="unbounded"/> 
      </xsd:sequence> 
    </xsd:complexType> 
  </xsd:element> 

  <xsd:element name="Utente"> 
    <xsd:complexType> 
      <xsd:sequence> 
        <xsd:element  ref="linkEsterno"  minOccurs="0" maxOccurs="1"/> 
        <xsd:element  ref="DataIscrizione"   minOccurs="1" maxOccurs="1"/> 
        <xsd:element  ref="CasaDiSviluppoPreferita"   minOccurs="0"  maxOccurs="1"/> 
        <xsd:element  ref="GenerePreferito"   minOccurs="0" maxOccurs="1"/> 
        <xsd:element ref="listaGiochi" minOccurs ="1" maxOccurs="1" />
        <xsd:element ref="listaPropic" minOccurs ="1" maxOccurs="1" />
      </xsd:sequence> 
        <xsd:attribute name="id_user" type="xsd:integer" use="required" /> 
    </xsd:complexType> 
  </xsd:element>
  
  <xsd:element  name="linkEsterno" type="xsd:string" /> 
  <xsd:element  name="DataIscrizione"  type="xsd:string" /> 
  <xsd:element  name="CasaDiSviluppoPreferita"  type="xsd:string" /> 
  <xsd:element  name="GenerePreferito"  type="xsd:string" />

  <xsd:element name="listaGiochi">
  <xsd:complexType>
    <xsd:sequence>
      <xsd:element ref="idGiocoPosseduto" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>
  </xsd:element>

  <xsd:element name="idGiocoPosseduto" type="xsd:integer" />

    <xsd:element name="listaPropic">
  <xsd:complexType>
    <xsd:sequence>
      <xsd:element ref="idPropic" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>
  </xsd:element>

  <xsd:element name="idPropic" type="xsd:integer" />

</xsd:schema> 